[workspace]
members = [
	"asset-registry",
	"auction",
	"authority",
	"benchmarking",
	"currencies",
	"gradually-update",
	"oracle",
	"oracle/runtime-api",
	"tokens",
	"tokens/runtime-api",
	"traits",
	"utilities",
	"vesting",
	"rewards",
	"nft",
	"xcm",
	"xtokens",
	"xcm-support",
	"unknown-tokens",
	"build-script-utils",
	"payments",
	"parameters",
]

resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[patch.'https://github.com/paritytech/polkadot-sdk']
frame-benchmarking = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
frame-support = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
frame-system = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
pallet-authority-discovery = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
pallet-authorship = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
pallet-babe = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
pallet-balances = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
pallet-elections-phragmen = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
pallet-message-queue = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
pallet-scheduler = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
pallet-session = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
pallet-staking = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
pallet-timestamp = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
pallet-treasury = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
pallet-vesting = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
pallet-transaction-payment = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sc-client-api = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sc-client-db = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sc-executor = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sc-executor-common = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sc-utils = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-api = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-application-crypto = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-arithmetic = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-authority-discovery = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-blockchain = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-consensus = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-consensus-slots = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-core = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-debug-derive = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-externalities = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-inherents = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-io = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-keystore = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-npos-elections = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-panic-handler = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-runtime = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-runtime-interface = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-session = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-staking = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-state-machine = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-std = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-storage = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-timestamp = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-trie = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-version = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-wasm-interface = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-tracing = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-maybe-compressed-blob = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
sp-weights = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
cumulus-primitives-core = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
cumulus-pallet-dmp-queue = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
cumulus-pallet-xcm = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
parachain-info = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
pallet-xcm = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
polkadot-core-primitives = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
polkadot-parachain-primitives = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
polkadot-primitives = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
xcm = { package = "staging-xcm", git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
xcm-executor = { package = "staging-xcm-executor", git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
xcm-builder = { package = "staging-xcm-builder", git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
xcm-simulator = { git = "https://github.com/paritytech//polkadot-sdk", branch = "release-polkadot-v1.2.1" }
