name: Test

on:
  pull_request:
    branches:
      - master
      - polkadot-**
    paths-ignore:
      - '**/README.md'
  push:
    branches:
      - master
      - polkadot-**
    paths-ignore:
      - '**/README.md'

env:
  toolchain: stable
  target: wasm32-unknown-unknown

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SCCACHE_CACHE_SIZE: "60G"
    steps:
    - uses: actions/checkout@v4
    - name: Install protobuf-compiler
      run: |
        sudo apt-get install protobuf-compiler
    - name: Install Rust stable
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
       toolchain: ${{ env.toolchain }}
       components: rustfmt, clippy
       target: ${{ env.target }}
    - name: Check format
      run: make dev-format-check
    - name: Install clippy
      run: rustup component add clippy
    - name: Update
      run: cargo update
    - name: Run clippy
      run: cargo clippy -- -D warnings
    - name: Check for Wasm
      run: make dev-check
    - name: Run tests
      run: make dev-test
