name: Test

on:
  pull_request:
    branches:
      - master
      - polkadot-**
    paths-ignore:
      - '**/README.md'
  push:
    branches:
      - master
      - polkadot-**
    paths-ignore:
      - '**/README.md'

env:
  toolchain: stable
  target: wasm32-unknown-unknown

jobs:
  build:
    strategy:
      matrix:
        flavour:
        - asset-registry
        - auction
        - authority
        - benchmarking
        - build-script-utils
        - currencies
        - gradually-update
        - nft
        - oracle
        - parameters
        - payments
        - rewards
        - tokens
        - traits
        - unknown-tokens
        - utilities
        - vesting
        - xcm
        - xcm-support
        - xtokens
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - name: Install protobuf-compiler
      run: |
        apt-get install protobuf-compiler
    - name: Install Rust stable
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
       toolchain: ${{ env.toolchain }}
       components: rustfmt, clippy
       target: ${{ env.target }}
    - name: Run cargo tests
      run: |
         make Cargo.toml
         cd ${{matrix.flavour}}
         cargo clippy -- -D warnings
         cargo test
    - name: cargo build
      run: |
         cd ${{matrix.flavour}}
         cargo build --release
